# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 10
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 10