version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/app
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 10
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 10
     runas: root