version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 10
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 10