version: 2.1

orbs: 
  python: circleci/python@2.0.3

jobs:
  build-and-test:
   machine:
    docker_layer_caching: true
   steps:
      - checkout
      - run:
          name: Docker image build
          command: docker build -t fantastic-gorilla:latest .
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Docker push
          command: docker push fantastic-gorilla:latest
      

workflows:
  develop:
    jobs:
      - build-and-test